{
 "title": "Reverse Words APP",
 "description": "Reverse Words APP Sample Dashboard with Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(total_reversed_words,ocp_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Reversed Words by Cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(total_reversed_words{ocp_cluster=~\"$cluster\"}) by (ocp_cluster)",
     "legendFormat": "{{ocp_cluster}}"
    }
   ]
  },
  {
   "title": "Endpoints Accesed by Cluster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(endpoints_accessed{ocp_cluster=~\"$cluster\"}) by (ocp_cluster,accessed_endpoint)",
     "legendFormat": "Cluster: {{ocp_cluster}} Endpoint: {{accessed_endpoint}}"
    }
   ]
  },
  {
   "title": "Total Reversed Words",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(total_reversed_words)" }
   ]
  }
 ]
}